name: deps

on:
  push:
  pull_request:

env:
  MIX_ENV: test

jobs:
  deps:
    name: Dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [1.15.7]
        otp: [26.1.2]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix deps.compile
